---
- name: Remediate httpd service on server01.aroque.com.br
  hosts: server01.aroque.com.br
  become: true

  tasks:
    - name: Unmask httpd service
      ansible.builtin.command:
        cmd: systemctl unmask httpd
        changed_when: false
        failed_when: false

    - name: Enable httpd service on boot
      ansible.builtin.systemd:
        name: httpd
        state: enabled

    - name: Start httpd service
      ansible.builtin.systemd:
        name: httpd
        state: started

    - name: Report remediation success
      ansible.builtin.set_stats:
        aggregate: false
        data:
          stats_remediation_action: "Started and enabled httpd service"
          stats_remediation_success: true